# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13order_manager.proto\x12\x05sales\"J\n\nOrderInput\x12\x15\n\rcustomer_code\x18\x01 \x01(\t\x12\x11\n\titem_code\x18\x02 \x01(\x05\x12\x12\n\nitem_count\x18\x03 \x01(\x05\"(\n\x0bOrderStatus\x12\x19\n\x11\x63onfirmation_code\x18\x01 \x01(\x05\"&\n\rCustomerInput\x12\x15\n\rcustomer_code\x18\x01 \x01(\t\"Q\n\rCustomerOrder\x12\x11\n\titem_code\x18\x01 \x01(\x05\x12\x12\n\nitem_count\x18\x02 \x01(\x05\x12\x19\n\x11\x63onfirmation_date\x18\x03 \x01(\t2\x80\x01\n\x0cOrderManager\x12\x33\n\nPlaceOrder\x12\x11.sales.OrderInput\x1a\x12.sales.OrderStatus\x12;\n\x0b\x46\x65tchOrders\x12\x14.sales.CustomerInput\x1a\x14.sales.CustomerOrder0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_manager_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDERINPUT']._serialized_start=30
  _globals['_ORDERINPUT']._serialized_end=104
  _globals['_ORDERSTATUS']._serialized_start=106
  _globals['_ORDERSTATUS']._serialized_end=146
  _globals['_CUSTOMERINPUT']._serialized_start=148
  _globals['_CUSTOMERINPUT']._serialized_end=186
  _globals['_CUSTOMERORDER']._serialized_start=188
  _globals['_CUSTOMERORDER']._serialized_end=269
  _globals['_ORDERMANAGER']._serialized_start=272
  _globals['_ORDERMANAGER']._serialized_end=400
# @@protoc_insertion_point(module_scope)
