/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Entropy */

#ifndef _Included_Entropy
#define _Included_Entropy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Entropy
 * Method:    captcha
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Entropy_captcha
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
